#!/usr/bin/env python

import json

from os import environ

# Environment configurations
DIR_OUT = environ.get('DIR_OUT')
CONVERSION_PROFILE = environ.get('CONVERSION_PROFILE')
HTTP_PORT = environ.get('HTTP_PORT')
OUTLIER_MODIFIER = environ.get('OUTLIER_MODIFIER')

SETTINGS_FILE = '/opt/node-makemkv/settings.json'
MAKEMKVCON_PATH = '/usr/local/bin/makemkvcon'

with open(SETTINGS_FILE, 'r') as fh:
    settings = json.loads(fh.read())

settings.update({
    'OUTPUT_DIR': DIR_OUT,
    'CONVERSION_PROFILE': CONVERSION_PROFILE,
    'SERVER_PORT': HTTP_PORT,
    'MAKEMKVCON_PATH': MAKEMKVCON_PATH,
    'OUTLIER_MODIFIER': OUTLIER_MODIFIER,
})

with open(SETTINGS_FILE, 'w') as fh:
    fh.write(json.dumps(settings))
